Repository gaucho-labs/leptos-hotkeys, pull requests merged in 2024-05, with the labels that each got.

#95 Final v0.2.0 release
  CHANGELOG.md
  Cargo.lock
  README.md
  leptos_hotkeys/Cargo.toml
Labels: chore

#102 Update docs to reflect the changes of `.code` usage
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  examples/demo/src/app.rs
  examples/ssr-demo/src/app.rs
Labels: documentation

#108 feat: fix hotkey keycode handling
  examples/ssr-demo/src/app.rs
  leptos_hotkeys/src/types.rs
  leptos_hotkeys/src/use_hotkeys.rs
Labels: bug

#112 Add `FromStr` impl for `Hotkey` and run tests on CI
  .github/workflows/ci.yml
  CHANGELOG.md
  leptos_hotkeys/src/hotkey.rs
Labels: improvement, chore

#114 Changes for new patch v0.2.1
  CHANGELOG.md
  README.md
  leptos_hotkeys/Cargo.toml
Labels: chore
