Repository gaucho-labs/leptos-hotkeys, pull requests merged in 2024-03, with the labels that each got.

#52 Markdownize and clean README
  README.md
Labels: documentation

#63 feat: remove csr + hydrate flags
  examples/demo/Cargo.toml
  examples/ssr-demo/Cargo.toml
  leptos_hotkeys/Cargo.toml
  leptos_hotkeys/src/hotkeys_provider.rs
  leptos_hotkeys/src/use_hotkeys.rs
Labels: improvement

#64 chore: add checks and formatting
  .editorconfig
  .github/actions/get-toolchain/action.yml
  .github/workflows/ci.yml
  .github/workflows/csr.yml
  .github/workflows/hydrate.yml
  CONTRIBUTING.md
  Cargo.lock
  Makefile.toml
  examples/demo/Cargo.lock
  examples/demo/src/app.rs
  examples/ssr-demo/Cargo.lock
  examples/ssr-demo/src/fileserv.rs
  leptos_hotkeys/src/hotkeys_provider.rs
  leptos_hotkeys/src/types.rs
  leptos_hotkeys/src/use_hotkeys.rs
Labels: chore

#67 Fix SSR
  Cargo.lock
  leptos_hotkeys/Cargo.toml
  leptos_hotkeys/src/hotkeys_provider.rs
  leptos_hotkeys/src/use_hotkeys.rs
Labels: chore

#69 Don't force Leptos' `nightly` feature
  .github/workflows/ci.yml
  Makefile.toml
  examples/ssr-demo/src/error_template.rs
  leptos_hotkeys/Cargo.toml
Labels: improvement

#71 Publish through CI using GIT tags
  .gitattributes
  .github/workflows/ci.yml
  CONTRIBUTING.md
Labels: chore

#73 Fix errors in publish workflows
  .github/workflows/ci.yml
Labels: chore

#74 Fix README path in leptos_hotkeys/Cargo.toml
  leptos_hotkeys/Cargo.toml
Labels: chore

#75 Add `--dry-run` to test crates publish workflow
  .github/workflows/ci.yml
Labels: chore

#76 Improve releasing instructions
  CONTRIBUTING.md
Labels: documentation

#77 Prepare v0.2.0 alpha release
  CHANGELOG.md
  Cargo.lock
  README.md
  examples/demo/dist/demo-8c3a73d0c1d9f788.js
  examples/demo/dist/demo-da27fb36ac81c1f1.js
  examples/demo/dist/index.html
  examples/demo/src/app.rs
  examples/ssr-demo/src/app.rs
  images/readme-cover.png
  leptos_hotkeys/Cargo.toml
  leptos_hotkeys/src/macros.rs
Labels: bug, documentation, chore

#78 Add write permissions to create-release workflow
  .github/workflows/ci.yml
Labels: chore

#85 Remove prelude and make modules private
  CHANGELOG.md
  leptos_hotkeys/src/lib.rs
  leptos_hotkeys/src/prelude.rs
Labels: improvement

#88 Rename `hotkeys_provider` module as `context`
  leptos_hotkeys/src/context.rs
  leptos_hotkeys/src/lib.rs
  leptos_hotkeys/src/use_hotkeys.rs
Labels: chore
